// Generated by CoffeeScript 1.3.3
(function() {

  window.CoffeeDate = {
    ISO_8601: /^\d{4}-[01]?\d-[0-3]?\d$/,
    SHORT_MONTHS: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  };

  Date.prototype.isToday = function() {
    var today;
    today = new Date;
    return this.getFullYear() === today.getFullYear() && this.getMonth() === today.getMonth() && this.getDate() === today.getDate();
  };

  Date.prototype.isThisYear = function() {
    return this.getFullYear() === (new Date).getFullYear();
  };

  Date.prototype.toStr = function(format) {
    switch (format) {
      case 'mon date':
        return "" + CoffeeDate.SHORT_MONTHS[this.getMonth()] + " " + (this.getDate());
      case 'mon year':
        return "" + CoffeeDate.SHORT_MONTHS[this.getMonth()] + " " + (this.getFullYear());
    }
  };

  CoffeeDate.isISO_8601 = function(dateStr) {
    return typeof dateStr === "string" && dateStr.match(CoffeeDate.ISO_8601) !== null;
  };

  CoffeeDate.fromISO_8601 = function(dateStr) {
    var parts;
    if (!CoffeeDate.isISO_8601(dateStr)) {
      return null;
    }
    parts = dateStr.split(/-/);
    return new Date(parts[0], parts[1] - 1, parts[2].slice(0, 2), 12);
  };

}).call(this);
