// Generated by CoffeeScript 1.3.3
(function() {

  describe('CoffeeDate', function() {
    describe('#isToday', function() {
      it('returns true for today', function() {
        return expect((new Date).isToday()).toBeTruthy();
      });
      return it('returns false for not today', function() {
        return expect((new Date(1000, 1, 1)).isToday()).toBeFalsy();
      });
    });
    describe('#isThisYear', function() {
      it('returns true for today', function() {
        return expect((new Date).isThisYear()).toBeTruthy();
      });
      return it('returns false for last year', function() {
        var date;
        date = new Date;
        date.setFullYear(date.getFullYear() - 1);
        return expect(date.isThisYear()).toBeFalsy();
      });
    });
    return describe('.fromISO_8601', function() {
      it('returns null for non-strings', function() {
        return expect(CoffeeDate.fromISO_8601(1)).toBeNull();
      });
      it('returns null for incorrectly formatted strings', function() {
        return expect(CoffeeDate.fromISO_8601('abcdef')).toBeNull();
      });
      return it('returns a date for correctly formatted strings', function() {
        var date;
        date = CoffeeDate.fromISO_8601('1234-12-31');
        expect(date).not.toBeNull();
        expect(date.getFullYear()).toEqual(1234);
        expect(date.getMonth()).toEqual(11);
        return expect(date.getDate()).toEqual(31);
      });
    });
  });

}).call(this);
